from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtConfi = QtWidgets.QTextEdit(self.centralwidget)
        self.txtConfi.setGeometry(QtCore.QRect(100, 10, 191, 31))
        self.txtConfi.setObjectName("txtConfi")
        self.btnOke = QtWidgets.QPushButton(self.centralwidget)
        self.btnOke.setGeometry(QtCore.QRect(300, 60, 91, 31))
        self.btnOke.setObjectName("btnOke")
        self.txtFrame = QtWidgets.QTextEdit(self.centralwidget)
        self.txtFrame.setGeometry(QtCore.QRect(100, 60, 191, 31))
        self.txtFrame.setObjectName("txtFrame")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 100, 91, 31))
        self.pushButton.setObjectName("pushButton")
        # self.btnRun = QtWidgets.QPushButton(self.centralwidget)
        # self.btnRun.setGeometry(QtCore.QRect(490, 420, 81, 41))
        # self.btnRun.setObjectName("btnRun")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(100, 140, 381, 321))
        self.listWidget.setObjectName("listWidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(100, 510, 441, 31))
        self.textEdit.setObjectName("textEdit")
        self.cmbYolo = QtWidgets.QComboBox(self.centralwidget)
        self.cmbYolo.setGeometry(QtCore.QRect(100, 470, 69, 31))
        self.cmbYolo.setObjectName("cmbYolo")
        self.btnRun2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnRun2.setGeometry(QtCore.QRect(100, 550, 75, 31))
        self.btnRun2.setObjectName("btnRun2")
        self.txtUrl = QtWidgets.QTextEdit(self.centralwidget)
        self.txtUrl.setGeometry(QtCore.QRect(100, 100, 191, 31))
        self.txtUrl.setObjectName("txtUrl")
        self.txtUrl.setReadOnly(True)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.btnRealtime = QtWidgets.QPushButton(self.centralwidget)
        self.btnRealtime.setGeometry(QtCore.QRect(400, 100, 75, 31))
        self.btnRealtime.setObjectName("btnRealtime")
        self.btnMedia = QtWidgets.QPushButton(self.centralwidget)
        self.btnMedia.setGeometry(QtCore.QRect(480, 100, 75, 31))
        self.btnMedia.setObjectName("btnMedia")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 763, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnOke.setText(_translate("MainWindow", "Upload"))
        self.label.setText(_translate("MainWindow", "Confidence"))
        self.label_2.setText(_translate("MainWindow", "Frame"))
        self.pushButton.setText(_translate("MainWindow", "Opent File"))
        # self.btnRun.setText(_translate("MainWindow", "RUN"))
        self.btnRun2.setText(_translate("MainWindow", "Run2"))
        self.label_3.setText(_translate("MainWindow", "URL"))
        self.btnRealtime.setText(_translate("MainWindow", "Realtime"))
        self.btnMedia.setText(_translate("MainWindow", "Media"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())